server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://shine1db.c5wtkpmvxzxl.ap-northeast-2.rds.amazonaws.com:3306/instagram_db # 변경해주세요
    username: admin
    password: emem1011
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전